### ISSUE TITLE
How to use slangtorch in a coda environment?

### ISSUE THREAD

**Issue by oliver-batchelor** [shader-slang/slang-torch#24]
I'm trying with python 3.11, torch 2.5.1 from conda/mamba. slangtorch 1.3.0 from pypi (otherwise I run into this as well https://github.com/shader-slang/slang-torch/issues/23)

If I use the system compilers I get this kind of error (both GCC and clang) 

```
/local/slang-torch/examples/inline-mlp-example/.slangtorch_cache/image-model/39a1e66c93673ceb/image-model.cpp:493:9: error: unknown type name 'SlangUInt'
typedef SlangUInt UInt;
        ^
/local/slang-torch/examples/inline-mlp-example/.slangtorch_cache/image-model/39a1e66c93673ceb/image-model.cpp:494:9: error: unknown type name 'SlangInt'
typedef SlangInt Int;

```
If I use compilers installed from mamba (GCC or clang again) I get this error:

```
/local/slang-torch/examples/inline-mlp-example/.slangtorch_cache/image-model/39a1e66c93673ceb/image-model.cpp:434:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
  434 | #pragma once
      |         ^
/local/slang-torch/examples/inline-mlp-example/.slangtorch_cache/image-model/39a1e66c93673ceb/image-model.cpp:476:10: fatal error: 'slang.h' file not found
  476 | #include "slang.h"
```

and in both cases a lot of warnings like this:

`/local/slang-torch/examples/inline-mlp-example/.slangtorch_cache/image-model/39a1e66c93673ceb/image-model_cuda.cu(1203): warning #177-D: function "surfCubemapLayeredwrite(T, cudaSurfaceObject_t, int, int, int, cudaSurfaceBoundaryMode) [with T=__half4]" was declared but never referenced
`

**Comment by oliver-batchelor** [comment]
Basic workaround here: https://github.com/shader-slang/slang-torch/issues/10

**Comment by saipraveenb25** [comment]
@oliver-batchelor: thank you for raising this issue! 

Could you try with a fresh environment that uses the latest slangtorch release (v1.3.2)? 
We fixed the "slang.h" regression there.

**Comment by oliver-batchelor** [comment]
> @oliver-batchelor: thank you for raising this issue!
> 
> Could you try with a fresh environment that uses the latest slangtorch release (v1.3.2)? We fixed the "slang.h" regression there.

Can confirm this works!
Thanks!
